### ISSUE TITLE
Drupal 8 port

### ISSUE THREAD

**Issue by andypost** [highweb/drupal-bricks#25]
There's some ways to port the module 
- entity reference based (already in core)
- use https://www.drupal.org/project/dynamic_entity_reference

Also treeable module needs to be ported and other dependencies as well

PS: very similar vision to content http://wimleers.com/blog/eaton-urbina-structured-intelligent-adaptive-content

**Comment by mirodietiker** [comment]
How about considering to collaborate with the Paragraphs project?

It also already has a well advanced port that originally emitted dynamic entity reference.

**Comment by tonystar** [comment]
That would be cool! Paragraphs is great, and my dream is to merge two these projects.

Do you have any ideas on how we can achieve that?

**Comment by tonystar** [comment]
@mirodietiker Anyway my dream is to merge two these projects. Do you have any ideas on how can we achieve that?

**Comment by mirodietiker** [comment]
We have spent some time discussing about release conditions and potential evolution of Paragraphs.

See also https://www.drupal.org/node/2601096#comment-10703330

It would be awesome if we can find a starting point towards that direction as a submodule, most likely in a 2.x branch (As a separate reusabe entity, extended / alternative widget, with nice UI integration).

**Comment by tonystar** [comment]
@andypost ported! stable! more powerful than ever!
Check out: https://uibricks.com and https://www.drupal.org/project/bricks!
Dynamic ER is in roadmap: https://www.drupal.org/node/2864108

@mirodietiker I'm ready! https://www.drupal.org/node/2838297
