### ISSUE TITLE
Atoms uses the same machine name as Scald for entities - 'atom'

### ISSUE THREAD

**Issue by markconroy** [highweb/drupal-bricks#29]
Hi Tony,

I mentioned this to you in Barcelona at the Twitter Bootstrap BoF. Atoms is using the same machine name 'atom' as Scald for its entities. This means you cannot install Atoms and Scald on the same website. I've posted the issue here: https://www.drupal.org/node/2580299

Mark.

**Comment by tonystar** [comment]
Hi Mark!

Thank you for the reporting! One of the Scald maintainers just replied:

> Scald is not using 'atom' as the machine name of its entity type; Scald entities are of type scald_atom. We're labeling them as atoms in the UI to make it slightly more user friendly, but that should not cause a crash.

**Comment by markconroy** [comment]
Great. All is well again so in the land of ATOM!

PS I hope you use Atom as your text editor!

**Comment by tonystar** [comment]
;D

> PS I hope you use Atom as your text editor!

Of course! Atoms module was created using Atom editor!

**Comment by tonystar** [comment]
Now it's Bricks ;)
